package com.example.ucm_discuss_be.aiInteraction;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import org.springframework.ai.chat.client.ChatClient;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;

@Service
@Slf4j
@RequiredArgsConstructor

public class AiService {
    private final ChatClient chatClient;
    private final AiRepository aiRepository;

    private static final String SYSTEM_INSTRUCTION = """
            Anda adalah @UCMDiscussAI, asisten dosen virtual di forum akademik Universitas Ciputra.
            Tugas Anda adalah menjawab pertanyaan singkat mahasiswa untuk memicu diskusi lanjutan.

            ATURAN MUTLAK (STRICT CONSTRAINTS):
            1. RUANG LINGKUP AKADEMIK: Anda HANYA diizinkan menjawab pertanyaan seputar materi kuliah, konsep, atau teori dari 3 program studi berikut: Informatika, Desain Komunikasi Visual (DKV), dan Manajemen.
            2. DI LUAR LINGKUP (OUT OF SCOPE): Jika pengguna menanyakan hal di luar 3 program studi tersebut, masalah pribadi, cuaca, politik, atau percakapan tidak relevan, Anda WAJIB menolak dengan sopan dalam 1 kalimat. (Contoh: "Maaf, ruang lingkup saya saat ini terbatas pada diskusi akademik Informatika, DKV, dan Manajemen.").
            3. PANJANG JAWABAN: Jawaban Anda TIDAK BOLEH melebihi 2 (dua) kalimat. Gunakan bahasa yang efektif, padat, dan langsung pada intinya.
            4. GAYA BAHASA: Profesional, edukatif, lugas, namun tetap suportif layaknya seorang asisten dosen.
            5. FORMAT OUTPUT: Berikan JAWABAN LANGSUNG. Jangan menambahkan sapaan pengantar seperti "Halo!", jangan mengulang pertanyaan, dan jangan menambahkan label "Generated by AI".
            """;

    public String generateAnswer(String question) {
        String response = chatClient
                .prompt()
                .system(SYSTEM_INSTRUCTION)
                .user(question)
                .call()
                .content();

        log.info("Response dari Gemini (Tanpa Thread): {}", response);
        return response;
    }

    public String getAnswerAndSave(Long threadId, String question) {
        String response = generateAnswer(question);

        log.info("Generated Gemini response for Thread {} context: {}", threadId, response);

        return response;
    }

}
