import { GoogleGenAI } from '@google/genai';

const ai = new GoogleGenAI({ 
    apiKey: process.env.EXPO_PUBLIC_GEMINI_API_KEY as string 
});

const MODEL_NAME = 'gemini-2.5-flash';

const SYSTEM_INSTRUCTION = `
Anda adalah @UCMDiscussAI, asisten dosen virtual di forum akademik Universitas Ciputra. 
Tugas Anda adalah menjawab pertanyaan singkat mahasiswa untuk memicu diskusi lanjutan.

ATURAN MUTLAK (STRICT CONSTRAINTS):
1. RUANG LINGKUP AKADEMIK: Anda HANYA diizinkan menjawab pertanyaan seputar materi kuliah, konsep, atau teori dari 3 program studi berikut: Informatika, Desain Komunikasi Visual (DKV), dan Manajemen.
2. DI LUAR LINGKUP (OUT OF SCOPE): Jika pengguna menanyakan hal di luar 3 program studi tersebut, masalah pribadi, cuaca, politik, atau percakapan tidak relevan, Anda WAJIB menolak dengan sopan dalam 1 kalimat. (Contoh: "Maaf, ruang lingkup saya saat ini terbatas pada diskusi akademik Informatika, DKV, dan Manajemen.").
3. PANJANG JAWABAN: Jawaban Anda TIDAK BOLEH melebihi 2 (dua) kalimat. Gunakan bahasa yang efektif, padat, dan langsung pada intinya.
4. GAYA BAHASA: Profesional, edukatif, lugas, namun tetap suportif layaknya seorang asisten dosen.
5. FORMAT OUTPUT: Berikan JAWABAN LANGSUNG. Jangan menambahkan sapaan pengantar seperti "Halo!", jangan mengulang pertanyaan, dan jangan menambahkan label "Generated by AI".
`;

export const AiService = {
    generateTagAnswer: async (userQuestion: string): Promise<string> => {
        try {
            if (!userQuestion || userQuestion.trim() === '') {
                throw new Error("Pertanyaan tidak boleh kosong");
            }

            const response = await ai.models.generateContent({
                model: MODEL_NAME,
                contents: userQuestion,
                config: {
                    systemInstruction: SYSTEM_INSTRUCTION,
                    temperature: 0.3,
                    maxOutputTokens: 300,
                }
            });

            const answerText = response.text;
            
            if (!answerText) {
                throw new Error("AI mengembalikan respons kosong.");
            }

            return answerText.trim();

        } catch (error) {
            console.error("Gemini AI Generation Error:", error);
            return "Maaf, sistem sedang kesulitan menjawab pertanyaan ini.";
        }
    }
};