spring.application.name=ucm-discuss-be

spring.config.import=optional:file:.env[.properties]

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

spring.datasource.url=${DB_Url}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.username=${DB_Username}
spring.datasource.password=${DB_Password}

# logging
logging.file.name=logs/app.log
logging.file.path=logs

# Oauth2 Credentials
spring.security.oauth2.client.registration.google.client-id=${Oauth_Client_Id}
spring.security.oauth2.client.registration.google.client-secret=${Oauth_Client_Secret}

#jwt secret key
security.jwt.secret-key=${JWT_Secret}
security.jwt.expiration-time=3600000

# Cloudinary configuration
cloudinary.url=cloudinary://${Cloudinary_API_Key}:${Cloudinary_API_Secret}@${Cloudinary_Cloud_Name}