FROM eclipse-temurin:21-jdk-jammy AS builder
WORKDIR /app

ENV GRADLE_OPTS="-Xmx1024m -XX:MaxMetaspaceSize=256m -Dorg.gradle.internal.http.connectionTimeout=120000 -Dorg.gradle.internal.http.socketTimeout=120000"

COPY gradlew .
COPY gradle gradle
COPY build.gradle.kts .
COPY settings.gradle.kts .
COPY src src

RUN echo "org.gradle.daemon=false" > gradle.properties && \
    echo "org.gradle.vfs.watch=false" >> gradle.properties

RUN chmod +x ./gradlew
# RUN ./gradlew dependencies --no-daemon

# COPY src src
RUN ./gradlew bootJar -x test --no-daemon --info --stacktrace

FROM eclipse-temurin:21-jre-alpine
WORKDIR /app

COPY --from=builder /app/build/libs/*-SNAPSHOT.jar app.jar

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]