services:
  db:
    image: mariadb:lts
    container_name: ucmdiscuss-db
    restart: always
    environment:
      MARIADB_DATABASE: ${DB_url}
      MARIADB_USER: ${DB_username}
      MARIADB_PASSWORD: ${DB_password}
      MARIADB_ROOT_PASSWORD: ${DB_password}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  api:
    build:
      context: .
      network: host
    container_name: ucmdiscuss-api
    restart: always
    ports:
      - "${DB_port}:8080"
    dns:
      - "8.8.8.8"
      - "1.1.1.1"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  db_data: